/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "\tThat's less sad. Have more rewards!": "\t那就没那么难过了。 获得更多奖励！",
    "Last gift rewards": "上次礼物奖励",
    "Main": "主页",
    "Naughty": "淘气",
    "Open a gift!": "打开一份礼物！",
    "Phase Diagram": "相图",
    "Toys": "玩具",
    "What could be hiding inside?": "里面可能藏着什么？",
    "Hold down to open multiple": "按住可以打开多个",
    "Have an extremely small chance of getting an actual game. (Santa is hard to impress.": "获得真正游戏的机会极小。 （圣诞老人很难给人留下深刻印象。",
    "Halve your gift rewards, but have a 10% chance of getting 40x more rewards.": "将您的礼物奖励减半，但有 10% 的机会获得 40 倍以上的奖励。",
    "Good Deeds Reward": "善行奖励",
    "Good Deeds": "善行",
    "Give away a 4th of your presents each time for a small chance of getting some toys.": "每次送出四分之一的礼物，就有机会获得一些玩具。",
    "Gacha game much?": "扭蛋游戏多吗？",
    "gifts": "礼物",
    "Coal": "煤",
    "christmas points": "圣诞点数",
    "Amazing Deeds": "惊人的事迹",
    "Active effects": "主动效果",
    "Less Naughty": "不那么淘气",
    "50 toy collections": "收藏 50 个玩具",
    "After all, what's wrong with collecting gifts on Easter too?": "毕竟，在复活节也收集礼物有什么问题？",
    "Automatically collect toys.": "自动收藏玩具。",
    "bonfire": "篝火",
    "coal": "煤",
    "Coal duplicator": "煤炭复印机",
    "Buy a pair of bellows to make the bonfire burn twice as good.": "买一副风箱，让篝火燃烧的更旺一倍。",
    "I mean, wouldn't it be better if you could collect all your toys at once?": "我的意思是，如果您可以一次收集所有玩具不是更好吗？",
    "It grows": "它长大了",
    "Huh?": "嗯？",
    "Generous Collecting": "大手笔的收藏",
    "Generous Donation": "慷慨捐赠",
    "Stoke the fire": "点燃火",
    "Swindle someone naughtily": "顽皮地欺骗某人",
    "Sell.": "出售.",
    "The bonfire is given more room, making it last longer and have better effects.": "篝火被给予更多的空间，使其持续时间更长，效果更好。",
    "The Easter^2 Tree": "复活节^2树-The Easter^2 Tree",
    "The Flame Tree": "火焰树-The Flame Tree",
    "The Oxygen Tree": "氧气树-The Oxygen Tree",
    "Toy collection": "玩具收藏",
    "The Tree of Life": "生命树-The Tree of Life",
    "toys": "玩具",
    "Unlock two coal \"buyables\". What the hell is a buyable anyway?": "解锁两个煤炭“可购买物品”。 到底什么是可买的？",
    "What is this, minecraft dot exe?": "这是什么，我的世界.exe？",
    "What's more relaxing than a nice bonfire?": "有什么比篝火晚会更让人放松的呢？",
    "With your coal, you convince someone to give you their present as well. Christmas season!": "用你的煤炭，你说服别人也给你礼物。 圣诞季！",
    "buy happiness": "购买快乐",
    "Buy some machines.": "买些机器。",
    "Buy some toys.": "买些玩具。",
    "can": "可以",
    "Flame.": "火焰.",
    "Capital investment": "资本投资",
    "Generous-er donations": "慷慨捐助",
    "It'll work out, somehow": "它会以某种方式解决",
    "Might as well go the whole way and bump your good deeds up even more.": "不妨一路走下去，让你的善行更上一层楼。",
    "money": "金钱",
    "Money": "金钱",
    "Money can buy gifts too": "钱也能买礼物",
    "Nothing. Decrease wait time by x2.": "没有什么。 将等待时间减少 x2。",
    "Reset Effects": "重置效果",
    "Start off strong by adding +4 to joy.": "开始时，在快乐中添加+4。",
    "Toy investment": "玩具投资",
    "Unlock money buyables. You still don't know what a buyable is.": "解锁金钱可买。 你仍然不知道什么是可购买的。",
    "What's wrong with buying some gifts every now and then?": "时不时买些礼物有什么错？",
    "That's less sad. Have more rewards!": "那就不那么难过了。 获得更多奖励！",
    "Blade": "刀刃",
    "Coal Mine": "Coal Mine",
    "machine parts": "机器零件",
    "Make Santa impressed enough to give a hundred times more gifts.": "让圣诞老人印象深刻，可以赠送一百倍的礼物。",
    "Maybe it's about time to find other sources of coal.": "也许是时候寻找其他煤炭来源了。",
    "Moar money.": "麻钱。",
    "Money Printer": "印钞机",
    "Opus Magnum": "大作",
    "Printer go brr": "打印机去brr",
    "Printing money has definitely never gone wrong before.": "印钱以前绝对不会出错。",
    "Sharp Blade": "锋利的刀片",
    "That's even less sad. Have even more rewards!": "那就更不难过了。 获得更多奖励！",
    "Time Warp": "时间扭曲",
    "Whoops!": "糟糕！",
    "Worker ploitation": "工人剥削",
    "You've broken the fabric of spacetime. What have you done?": "你打破了时空的结构。 你做了什么？",
    "It grows, larger.": "它长大了，变大了。",
    "Toy megacollection": "玩具大集合",
    "Make it sharper!": "让它更锋利！",
    "Automatically open gifts.": "自动打开礼物。",
    "Make Einstein angrier.": "让爱因斯坦更生气。",
    "Time warp": "时间扭曲",
    "That's pretty happy if I must say. Have even more rewards!": "如果我必须说，那真是太高兴了。 获得更多奖励！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\t\t": "\t\t",
    "\t": "\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Your best gifts is ": "你最多时候的礼物是 ",
    "Joy: ": "乐趣: ",
    "Your best money is ": "你最多时候的钱是",
    "Your best machine parts is ": "您最多时候的机器零件是 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "s til next gift": "秒 到下一个礼物",
    " to gift rewards": " 礼物奖励",
    " to present rewards": " 礼物奖励",
    " to coal rewards": " 煤奖励",
    " to coal gain": " 煤增益",
    " to gift gain": " 礼物增益",
    " to present gain": " 礼物增益",
    " rewards when opening gifts": " 开启礼物时的奖励",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have made a total of (.+) gifts$/, '您总共制作了 $1 份礼物'],
    [/^Sell your toy collection for (.+) money.$/, '以 $1 的价格出售您的玩具收藏。'],
    [/^giving (.+) to joy, but you are losing (.+) of it every second$/, '给予 $1 快乐，但你每秒失去 $2'],
    [/^After opening (.+) gifts, maybe it\'s time to build something to do it for you.$/, '打开 $1 份礼物后，也许是时候为您打造一些东西了。'],
    [/^You have (.+) coal in the burning pile, but (.+) of it is being burnt every second.$/, '您的燃烧堆中有 $1 煤，但每秒有 $2 的煤正在燃烧。'],
    [/^You have made a total of (.+) machine parts$/, '您总共制造了 $1 个机器零件'],
    [/^You have made a total of (.+) money$/, '你总共赚了 $1 钱'],
    [/^You have (.+) money$/, '你有 $1 金钱'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Automatically opens (.+) gifts per tick\n\t\t\t\t(.+) machine parts$/, '每 tick 自动开启 $1 个礼物\n\t\t\t\t $2 个机器零件'],
    [/^(.+) money gain\n\t\t\t\t(.+) machine parts$/, '$1 金钱收益\n\t\t\t\t$2 机器零件'],
    [/^Next at (.+) money$/, '下一个在 $1 金钱'],
    [/^(.+) present gain speed\n\t\t\t\t(.+) machine parts$/, '$1 礼物增益速度\n\t\t\t\t $2机器零件'],
    [/^Size\: (.+)\n\t\t\t\t(.+) joy\n\t\t\t\t(.+) to toy gain$/, '尺寸：$1\n\t\t\t\t$2 快乐\n\t\t\t\t$3 到玩具增益'],
    [/^Size\: (.+)\n\t\t\t\t\+(.+) joy$/, '尺寸\: $1\n\t\t\t\t\+$2 玩具'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^(.+)\/(.+) coal$/, '$1\/$2 煤'],
	[/^(.+)\/(.+) fire$/, '$1\/$2 火'],
	[/^(.+)\/(.+) toys$/, '$1\/$2 玩具'],
	[/^(.+)\/(.+) toy collections$/, '$1\/$2 玩具收藏'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) toys.$/, '$1 玩具。'],
    [/^([\d\.]+) toys.$/, '$1 玩具。'],
    [/^([\d\.,]+) coal.$/, '$1 煤。'],
    [/^([\d\.,]+) machine parts$/, '$1 机器零件'],
    [/^([\d\.,]+) money$/, '$1 金钱'],
    [/^([\d\.,]+) gifts$/, '$1 礼物'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: ([\d\.,]+)$/, '成本：$1'],
    [/^Cost: ([\d\.]+)e([\d\.,]+)$/, '成本：$1e$2'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);